{
 "title": "k8s-alert",
 "description": "dashboard id : 14858",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "Node",
    "label": "Node",
    "query": {
     "query": "label_values(kube_node_info{origin_prometheus=~\"$origin_prometheus\"},node)"
    }
   },
   {
    "name": "origin_prometheus",
    "label": "DataSource",
    "query": {
     "query": "label_values(origin_prometheus)"
    }
   },
   {
    "name": "job",
    "label": "JOB",
    "query": {
     "query": "label_values(node_uname_info{origin_prometheus=~\"$origin_prometheus\"}, job)"
    }
   },
   {
    "name": "total",
    "label": "主机数",
    "query": {
     "query": "query_result(count(node_uname_info{origin_prometheus=~\"$origin_prometheus\",job=~\"$job\"}))"
    }
   },
   {
    "name": "NameSpace",
    "label": "NameSpace",
    "query": {
     "query": "label_values(kube_namespace_labels{origin_prometheus=~\"$origin_prometheus\"},namespace)"
    }
   },
   {
    "name": "Container",
    "label": "Container",
    "query": {
     "query": "label_values(kube_pod_container_info{origin_prometheus=~\"$origin_prometheus\",namespace=~\"$NameSpace\"},container)"
    }
   },
   {
    "name": "Pod",
    "label": "Pod",
    "query": {
     "query": "label_values(kube_pod_container_info{origin_prometheus=~\"$origin_prometheus\",namespace=~\"$NameSpace\",container=~\"$Container\"},pod)"
    }
   },
   {
    "name": "pod_total",
    "label": "pod數量",
    "query": {
     "query": "query_result(count(kube_pod_container_info{origin_prometheus=~\"$origin_prometheus\",pod=~\"$Pod\",container =~\"$Container\",namespace=~\"$NameSpace\"}))"
    }
   },
   {
    "name": "mq_total",
    "label": "rabbitmq數量",
    "query": {
     "query": "query_result(sum(rabbitmq_identity_info{namespace=\"default\"}))"
    }
   }
  ]
 },
 "panels": [
  { "title": "Alerts Status", "type": "alertlist", "gridPos": { "h": 9, "w": 8, "x": 0, "y": 0 } },
  { "title": "Alerts Log", "type": "alertlist", "gridPos": { "h": 9, "w": 16, "x": 8, "y": 0 } },
  {
   "title": "Container Resource Overview【Total Pods：$pod_total 】",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "container_memory_working_set_bytes{origin_prometheus=~\"$origin_prometheus\",pod=~\"$Pod\",container =~\"$Container\",namespace=~\"$NameSpace\",node=~\"^$Node$\"}",
     "legendFormat": "memory"
    },
    {
     "expr": "(rate (container_cpu_usage_seconds_total{origin_prometheus=~\"$origin_prometheus\",pod=~\"$Pod\",container =~\"$Container\",namespace=~\"$NameSpace\",node=~\"^$Node$\"}[5m]) /8) * 100",
     "legendFormat": "cpu"
    },
    {
     "expr": "kube_pod_container_status_running{pod=~\"$Pod\",container =~\"$Container\",namespace=~\"$NameSpace\"}",
     "legendFormat": "status"
    },
    {
     "expr": "kube_pod_container_status_restarts_total{pod=~\"$Pod\",container =~\"$Container\",namespace=~\"$NameSpace\"}",
     "legendFormat": "restart"
    },
    {
     "expr": "sum (rate (container_network_receive_bytes_total{origin_prometheus=~\"$origin_prometheus\",pod=~\"$Pod\",image!=\"\",name=~\"^k8s_.*\",node=~\"^$Node$\",namespace=~\"$NameSpace\",pod=~\".*$Container.*\"}[2m])) by (pod)*8",
     "legendFormat": "incoming"
    },
    {
     "expr": "sum (rate (container_network_transmit_bytes_total{origin_prometheus=~\"$origin_prometheus\",pod=~\"$Pod\",image!=\"\",name=~\"^k8s_.*\",node=~\"^$Node$\",namespace=~\"$NameSpace\",pod=~\".*$Container.*\"}[2m])) by (pod)*8",
     "legendFormat": "outgoing"
    },
    {
     "expr": "time () - container_start_time_seconds{origin_prometheus=~\"$origin_prometheus\",pod=~\"$Pod\",container =~\"$Container\",namespace=~\"$NameSpace\",node=~\"^$Node$\"}",
     "legendFormat": "uptime"
    },
    {
     "expr": "kube_pod_container_info{pod=~\"$Pod\",container =~\"$Container\",namespace=~\"$NameSpace\"} - 0"
    }
   ]
  },
  {
   "title": "k8s - Nodes Resource Overview【Total Nodes：$total 】",
   "type": "table-old",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "count(node_cpu_seconds_total{origin_prometheus=~\"$origin_prometheus\",job=~\"$job\",mode='system'}) by (instance)",
     "legendFormat": "CPU core"
    },
    {
     "expr": "node_memory_MemTotal_bytes{origin_prometheus=~\"$origin_prometheus\",job=~\"$job\"} - 0",
     "legendFormat": "Memory"
    },
    {
     "expr": "node_load5{origin_prometheus=~\"$origin_prometheus\",job=~\"$job\"}",
     "legendFormat": "5 min load"
    },
    {
     "expr": "(1 - avg(rate(node_cpu_seconds_total{origin_prometheus=~\"$origin_prometheus\",job=~\"$job\",mode=\"idle\"}[1m])) by (instance)) * 100",
     "legendFormat": "CPU Usage"
    },
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes{origin_prometheus=~\"$origin_prometheus\",job=~\"$job\"} / (node_memory_MemTotal_bytes{origin_prometheus=~\"$origin_prometheus\",job=~\"$job\"})))* 100",
     "legendFormat": "Memory Usage"
    },
    {
     "expr": "max((node_filesystem_size_bytes{origin_prometheus=~\"$origin_prometheus\",job=~\"$job\",fstype=~\"ext.?|xfs\"}-node_filesystem_free_bytes{origin_prometheus=~\"$origin_prometheus\",job=~\"$job\",fstype=~\"ext.?|xfs\"}) *100/(node_filesystem_avail_bytes {origin_prometheus=~\"$origin_prometheus\",job=~\"$job\",fstype=~\"ext.?|xfs\"}+(node_filesystem_size_bytes{origin_prometheus=~\"$origin_prometheus\",job=~\"$job\",fstype=~\"ext.?|xfs\"}-node_filesystem_free_bytes{origin_prometheus=~\"$origin_prometheus\",job=~\"$job\",fstype=~\"ext.?|xfs\"})))by(instance)",
     "legendFormat": "Disk Usage"
    },
    {
     "expr": "max(rate(node_network_receive_bytes_total{origin_prometheus=~\"$origin_prometheus\",job=~\"$job\",device=~\"eth0\"}[1m])*8) by (instance)",
     "legendFormat": "Incoming traffic"
    },
    {
     "expr": "max(rate(node_network_transmit_bytes_total{origin_prometheus=~\"$origin_prometheus\",job=~\"$job\",device=~\"eth0\"}[1m])*8) by (instance)",
     "legendFormat": "outgoing traffic"
    }
   ]
  },
  {
   "title": "k8S - Node Total Traffic (Threshold：traffic  > 100 Mbps)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "sum(max(rate(node_network_receive_bytes_total{device=~\"eth0\"}[1m])*8) by (instance))",
     "legendFormat": "Total_incoming"
    },
    {
     "expr": "sum(max(rate(node_network_transmit_bytes_total{device=~\"eth0\"}[1m])*8) by (instance))",
     "legendFormat": "Total_outgoing"
    }
   ]
  },
  {
   "title": "Pods Status Monitoring",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true,
   "panels": [
    {
     "title": "Service Pods available",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 25 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "kube_statefulset_status_replicas_current{namespace=\"default\"}",
       "legendFormat": "{{statefulset}}"
      },
      {
       "expr": "kube_daemonset_status_number_available{namespace=\"default\"}",
       "legendFormat": "{{daemonset}}"
      },
      {
       "expr": "kube_deployment_status_replicas_available{namespace=\"default\"}",
       "legendFormat": "{{deployment}}"
      }
     ]
    },
    {
     "title": "Istio Pods available",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 25 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "kube_statefulset_status_replicas_current{namespace=\"istio-system\"}",
       "legendFormat": "{{statefulset}}"
      },
      {
       "expr": "kube_daemonset_status_number_available{namespace=\"istio-system\"}",
       "legendFormat": "{{daemonset}}"
      },
      {
       "expr": "kube_deployment_status_replicas_available{namespace=\"istio-system\"}",
       "legendFormat": "{{deployment}}"
      }
     ]
    },
    {
     "title": "Container Restart",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 32 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "kube_pod_container_status_restarts_total{namespace=\"default\",container!=\"istio-proxy\"}",
       "legendFormat": "{{pod}}：{{container}}"
      },
      {
       "expr": "kube_pod_container_status_restarts_total{namespace=\"istio-system\",container!=\"istio-proxy\",container!=\"istio-init-crd-10\",container!=\"istio-init-crd-11\",container!=\"istio-init-crd-14\"}",
       "legendFormat": "{{pod}}：{{container}}"
      }
     ]
    },
    {
     "title": "Container Status of running (Threshold：current  < 1)",
     "type": "graph",
     "description": "current : 1 (Running)\ncurrent : 0 (Died)",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 32 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "kube_pod_container_status_running{namespace=\"default\",container!=\"istio-proxy\"}",
       "legendFormat": "{{pod}}：{{container}}"
      },
      {
       "expr": "kube_pod_container_status_running{namespace=\"istio-system\",container!=\"istio-proxy\",container!=\"istio-init-crd-10\",container!=\"istio-init-crd-11\",container!=\"istio-init-crd-14\"}",
       "legendFormat": "{{pod}}：{{container}}"
      }
     ]
    },
    {
     "title": "Container CPU Usage",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 39 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "(rate (container_cpu_usage_seconds_total{origin_prometheus=~\"$origin_prometheus\",pod=~\"$Pod\",container =~\"$Container\",namespace=~\"$NameSpace\",node=~\"^$Node$\"}[5m]) /8) * 100",
       "legendFormat": "{{node}} : {{pod}}：{{container}}"
      }
     ]
    },
    {
     "title": "Container Memory Usage",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 39 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "container_memory_working_set_bytes{origin_prometheus=~\"$origin_prometheus\",pod=~\"$Pod\",container =~\"$Container\",namespace=~\"$NameSpace\",node=~\"^$Node$\"}",
       "legendFormat": "{{node}} : {{pod}}：{{container}}"
      }
     ]
    },
    {
     "title": "Container Incoming traffic (total)",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 48 },
     "yaxes": [
      { "format": "bps" }
     ],
     "targets": [
      {
       "expr": "sum (sum (rate (container_network_receive_bytes_total{origin_prometheus=~\"$origin_prometheus\",pod=~\"$Pod\",image!=\"\",name=~\"^k8s_.*\",node=~\"^$Node$\",namespace=~\"$NameSpace\",pod=~\".*$Container.*\"}[1m])) by (pod)* on(pod)  group_right kube_pod_container_info) by(container)*8",
       "legendFormat": "Incoming : {{ container }}"
      }
     ]
    },
    {
     "title": "Container Outgoing traffic  (total)",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 48 },
     "yaxes": [
      { "format": "bps" }
     ],
     "targets": [
      {
       "expr": "sum (sum (rate (container_network_transmit_bytes_total{origin_prometheus=~\"$origin_prometheus\",pod=~\"$Pod\",image!=\"\",name=~\"^k8s_.*\",node=~\"^$Node$\",namespace=~\"$NameSpace\",pod=~\".*$Container.*\"}[2m])) by (pod)* on(pod)  group_right kube_pod_container_info) by(container) *8",
       "legendFormat": "Outgoing : {{ container }}"
      }
     ]
    }
   ]
  },
  {
   "title": "K8S Nodes Resource Monitoring",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "panels": [
    {
     "title": "K8S  - Nodes Status (Threshold：Number of node  < 3)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 26 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "sum(kube_node_info)", "legendFormat": "Nodes available" },
      {
       "expr": "sum(kube_node_spec_unschedulable)",
       "legendFormat": "Nodes Unavailable"
      }
     ]
    },
    {
     "title": "K8S - Nodes CPU Usage (Threshold：Usage  > 80%)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 26 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "(1 - avg(rate(node_cpu_seconds_total{mode=\"idle\"}[1m])) by (instance)) * 100",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "K8S - Nodes Disk Usage (Threshold：Usage  > 80%)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 33 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "(node_filesystem_size_bytes{fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}-node_filesystem_free_bytes{fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}) *100/(node_filesystem_avail_bytes {fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}+(node_filesystem_size_bytes{fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}-node_filesystem_free_bytes{fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}))",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "K8S - Nodes Memory Usage (Threshold：Usage  > 80%)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 33 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "(1 - (node_memory_MemAvailable_bytes / (node_memory_MemTotal_bytes)))* 100",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "k8S - Nodes Incoming traffic (Threshold：traffic  > 15 Mbps)",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 40 },
     "yaxes": [
      { "format": "bps" }
     ],
     "targets": [
      {
       "expr": "max(rate(node_network_receive_bytes_total{device=~\"eth0\"}[1m])*8) by (instance)",
       "legendFormat": "Incoming : {{instance}}"
      }
     ]
    },
    {
     "title": "k8S - Nodes Outgoing traffic (Threshold：traffic  > 15 Mbps)",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 40 },
     "yaxes": [
      { "format": "bps" }
     ],
     "targets": [
      {
       "expr": "max(rate(node_network_transmit_bytes_total{device=~\"eth0\"}[1m])*8) by (instance)",
       "legendFormat": "Outgoing : {{instance}}"
      }
     ]
    }
   ]
  }
 ]
}